# Generated by Django 2.1.3 on 2018-12-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', 'test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='genome',
            field=models.FileField(blank=True, upload_to='genomes/'),
        ),
    ]
