# Generated by Django 2.1.3 on 2018-12-11 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(blank=True, max_length=75)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('race', models.CharField(blank=True, choices=[('american indian', 'American Indian'), ('alaska native', 'Alaska Native'), ('asian', 'Asian'), ('white', 'White'), ('black or african american', 'Black or African American'), ('native hawaiian', 'Native Hawaiian'), ('pacific islander', 'Pacific Islander'), ('hispanic', 'Hispanic'), ('two or more races', 'Two or more races')], max_length=50)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
