# Generated by Django 2.1.3 on 2018-12-12 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0001_auto_20181211_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_first_visit',
            field=models.DateField(default=datetime.date(2018, 12, 12)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=50),
        ),
    ]
