# Generated by Django 2.1.3 on 2018-12-12 03:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_auto_20181212_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_of_first_visit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
