# Generated by Django 2.1.3 on 2018-12-21 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinical', '0006_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthEncounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=100)),
                ('type_of_encounter', models.CharField(choices=[('surgery', 'Surgery'), ('routine physical', 'Routine Physical'), ('general illness', 'General Illness'), ('emergency room', 'Emergency Room')], max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_first_visit',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='race',
            field=models.CharField(blank=True, choices=[('american indian', 'American Indian'), ('alaska native', 'Alaska Native'), ('asian', 'Asian'), ('white', 'White'), ('black or african american', 'Black or African American'), ('native hawaiian', 'Native Hawaiian'), ('pacific islander', 'Pacific Islander'), ('hispanic', 'Hispanic'), ('two or more races', 'Two or more races')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AddField(
            model_name='healthencounter',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinical.Patient'),
        ),
        migrations.AddField(
            model_name='healthencounter',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
