# Generated by Django 2.1.3 on 2018-12-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0007_auto_20181220_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthencounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.Patient'),
        ),
    ]
