# Generated by Django 2.1.3 on 2018-12-23 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_auto_20181221_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chronic_condition', models.BooleanField(default=False)),
                ('prognosis', models.CharField(blank=True, max_length=50)),
                ('time_of_diagnosis', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('doses', models.CharField(max_length=100)),
                ('refill', models.CharField(max_length=100)),
                ('instructions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('date_of_death', models.DateField(blank=True)),
                ('relationship', models.CharField(choices=[('brother', 'Brother'), ('sister', 'Sister'), ('father', 'Father'), ('mother', 'Mother'), ('grandfather paternal', 'Grandfather Paternal'), ('grandmother paternal', 'Grandmother Paternal'), ('grandfather maternal', 'Grandfather Maternal'), ('grandmother maternal', 'Grandmother Maternal')], max_length=50)),
                ('cause_of_death', models.CharField(blank=True, max_length=50)),
                ('diseases', models.ManyToManyField(to='clinical.Disease')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='related_medications',
            field=models.ManyToManyField(to='clinical.Medication'),
        ),
    ]
