# Generated by Django 2.1.3 on 2018-12-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0009_auto_20181223_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relative',
            name='date_of_death',
            field=models.DateField(blank=True, null=True),
        ),
    ]
